
#### general settings

name: CSNorm_log
use_tb_logger: False
model: CSNorm
gpu_ids: [0]

#### datasets

datasets:
  train:
    name: data_train
    mode: JSH_train
    dataroot_gt: 'TRAINDATA/GT' # path to training Clean images
    dataroot_lq: 'TRAINDATA/LQ' # path to training Noisy images

    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 4
    GT_size: 256
    use_flip: true
    use_rot: true
    color: RGB

  val:
    name: data_val
    mode: JSH_val
    dataroot_gt: '.VALDATA/GT' # path to validation Clean images
    dataroot_lq: '.VALDATA/LQ' # path to validation Noisy images

#### network structures

network_G:
  which_model_G:
      subnet_type: Resnet
  in_nc: 3
  out_nc: 3
  block_num: [8, 8]
  scale: 2
  init: xavier


#### path

path:
  root: ./
  pretrain_model_G:
  strict_load: true
  resume_state: ~


#### training settings: learning rate scheme, loss

train:
  lr_G: !!float 2e-4
  beta1: 0.9
  beta2: 0.999
  niter: 600000
  warmup_iter: -1  # no warm up

  lr_scheme: MultiStepLR
  lr_steps: [50000, 80000, 100000, 200000, 500000]
  lr_gamma: 0.5

  pixel_criterion_forw: l2
  pixel_criterion_back: l2
  pixel_criterion_hist: l2

  manual_seed: 9

  val_freq: !!float 100

  vgg16_model:

  lambda_fit_forw: 10
  lambda_vgg_forw: 0.
  lambda_structure_forw: 1
  lambda_orth_forw: 1

  lambda_rec_back: 1
  lambda_structure_back: 1
  lambda_orth_back: 1

  weight_decay_G: !!float 1e-8
  gradient_clipping: 10


#### logger

logger:
  print_freq: 40
  save_checkpoint_freq: !!float 5000
